### ISSUE TITLE
changes from October make it harder to understand

### ISSUE THREAD

**Issue by jamesmanning** [codecov/example-csharp#12]
There was a change made in October that looks like it was very useful and came from the experience of StyleCopAnalyzers getting supported on codecov, but the way it reads makes it sound like the change was meant to guide the person who was going to update the readme.md instead of being pasted in?

https://github.com/codecov/example-csharp/commit/2ade5041e115d6383779a3ecaf397406c8c68f39

> Based on this experience, I recommend the following changes to the documentation.

@stevepeak apologies if I'm just misinterpreting the doc and it's intentional as-is

**Comment by stevepeak** [comment]
Hey @jamesmanning thank you for pointing this out. I'll work on cleaning up the example repo today. 👍 It fell off my radar, thanks for poking it

**Comment by larzw** [comment]
@jamesmanning, the readme has been cleaned up.

/cc @stevepeak
