### ISSUE TITLE
Other coverage formats?

### ISSUE THREAD

**Issue by onovotny** [codecov/example-csharp#18]
Do you support coverage formats other than OpenCover -- like JetBrains' DetailedXML format? Alternatively, is there a transform or adapter we can implement?

OpenCover isn't working well for .NET Core projects currently but JetBrains dotCover works. We would like to get that data into codecov.

**Comment by stevepeak** [comment]
Hey @onovotny we support every format we have seen thus far. About 15 different formats. 
If you have an example of the DetailedXML format I can verify it can be processed, and if not add it to our list of acceptable upload formats.

**Comment by onovotny** [comment]
[coverage-rx.zip](https://github.com/codecov/example-csharp/files/854935/coverage-rx.zip)

That's great news -- I've attached a dotCover output for Rx.NET.

**Comment by onovotny** [comment]
One other question -- are we able to have two logical entities for a given Git Repo? For reasons, we have both Ix.NET and Rx.NET in the same GitHub repo. We'd like to track code coverage separately for them as they build and version independently. 

So effectively we need two things that point to the same repo but with different access tokens/config/something?

**Comment by stevepeak** [comment]
> We'd like to track code coverage separately for them as they build and version independently.

I believe our Flags do the trick: http://docs.codecov.io/docs/flags

**Comment by stevepeak** [comment]
We do not support that format. But I can add it today ;)

**Comment by onovotny** [comment]
That looks like exactly what we need -- I assume that would go in the repo root:
https://github.com/Reactive-Extensions/Rx.NET

And then when we build https://github.com/Reactive-Extensions/Rx.NET/Rx.NET/Source/System.Reactive.sln
or https://github.com/Reactive-Extensions/Rx.NET/Ix.NET/Source/Ix.NET.sln it'd work since we'd specify /Ix.NET and /Rx.NET as the paths for the flags?

**Comment by onovotny** [comment]
The part that's a bit unclear from a first pass at the docs is whether configuring the paths for flags in the yaml file is enough or if we also have to specify the -F parameter in the upload?

**Comment by stevepeak** [comment]
There are some `null` bytes at the head of the file. Is that expected?

**Comment by onovotny** [comment]
It should just be a utf-8 xml file...?

**Comment by stevepeak** [comment]
> The part that's a bit unclear from a first pass at the docs is whether configuring the paths for flags in the yaml file is enough or if we also have to specify the -F parameter in the upload?

For now you must upload to a flag via `-F` for data to be collected in that flag. This is changing in about a week to not require an upload. codecov/support#366

Paths are used to filter out specific locations that concern that flag.

> work since we'd specify /Ix.NET and /Rx.NET as the paths for the flags?

Yes.

```yaml
flags:
  lx:
    paths:
      - "*/lx.Net"
  rx:
    paths:
      - "*/rx.Net"
```

```
bash <(curl -s https://codecov.io/bash) -F lx,rx
```

**Comment by stevepeak** [comment]
Yea seeing `0xef` leading the file. Very odd.

**Comment by onovotny** [comment]
That is the Byte Order Mark that you'll often see in UTF-8 files:
https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by stevepeak** [comment]
Hum. No problem. I'll remove non-ascii chars from start of string.

**Comment by onovotny** [comment]
I would not recommend that -- Identifiers in .NET may be Unicode -- those are valid. Converting/interpreting as ASCII is probably incorrect behavior. The data should be read and stored UTF-8.

**Comment by stevepeak** [comment]
Please correct me if I'm wrong, but concerning the coverage details the non-ascii chars are irrelevant. Striping them our for processing purposes would have no impact on the results of the coverage report.

**Comment by onovotny** [comment]
depends on whether you store/display method names anywhere -- if not, and all you care about is line and column numbers, then it shouldn't matter. Also how do you display the source code?

**Comment by stevepeak** [comment]
> depends on whether you store/display method names anywhere

In the future, yes. But for now we do not store method names.

> Also how do you display the source code?

We pull it from Github on the fly 👍

**Comment by onovotny** [comment]
Thanks for all of this -- I'll aim to update Rx.NET later this week/weekend to integrate here. I like that a token isn't required for public repo's built from AppVeyor, so we can get coverage reports from PR's too.

**Comment by stevepeak** [comment]
@onovotny great! I'll be deploying the support for this jetbrains xml format today/tomorrow.

**Comment by citizenmatt** [comment]
Just an FYI, as I hit this issue parsing the XML file - the format supports nested types. So you can have multiple nested `Type` elements. If you don't handle that, then your coverage totals look suspiciously low :)

**Comment by stevepeak** [comment]
Deployed 👍 Looking forward to your feedback. Thank you!

**Comment by bbrandt** [comment]
@stevepeak Were you able to address @citizenmatt 's concern in your Mar 22nd deploy?

**Comment by stevepeak** [comment]
We do support Jetbrains XML. To the best of my knowledge we currently support *every* known coverage output format. @bbrandt Do you have an example of an output that was not processed properly? Thanks!

> Closing issue since Jetbrains is now supported. Please contact our [support](https://codecov.io/support) for one-on-one chat with our team. Thank you all! 👍

**Comment by bbrandt** [comment]
Just kicking the tires at this point.  I'm going to need to go through it with one of my open source projects. 
 Thanks!
