### ISSUE TITLE
codecov coverage always return 0

### ISSUE THREAD

**Issue by WeihanLi** [codecov/example-csharp#19]
I've my project integrated with appveyor,you can view my project [here](https://github.com/WeihanLi/MvcSimplePager),and I can get the report on the codecov.io site.
When I view the test coverage offline,I can get a 78.3%.I do not know where I did incorrectly.Hope anyone can help.

**Comment by stevepeak** [comment]
Hey @WeihanLi you can review the raw uploads from the Commit Build: https://codecov.io/gh/WeihanLi/MvcSimplePager/commit/3673838ca00bb418042edb2b1e5acdc77ed8bb64/build

Indeed the uploaded coverage is 0%. I suggest you run coverage locally to debug. There likely is some configuration issue before Codecov is called.

Thank you,
Steve
