### ISSUE TITLE
AppVeyor sample

### ISSUE THREAD

**Issue by ddur** [codecov/example-csharp#6]
.

**Comment by ddur** [comment]
AppVeyor VS 2015 environment
Python sample does not work if AppVeyor fetches repository as zip archive

**Comment by ddur** [comment]
Codecov is crap. Documentation is crap. 
When I finally got the upload, it is not shown on projects page but on special reference in build result.
Badge is "undefined".
Coveralls.io works fine on first attempt.

**Comment by RyanCopley** [comment]
> Codecov is crap. Documentation is crap.

As not-a-codecov employee, you're an ass. Instead of being rude, why don't you use your thinking cap and post relevant info so that Steve can help you appropriately.

**Comment by ddur** [comment]
All they have to do is small "man page" for two scripts they provide.
And couple notes for supported AppVeyor/VS environments.
Samples are great for start but incomplete.

You as user and not-a-codecov employee are the same as me ;) and you should be on my (client) side.

**Comment by ddur** [comment]
@RyanCopley
>As not-a-codecov employee, you're an ass.

You are very kind and polite.
I guess you do not know better. Thank you.
