### ISSUE TITLE
Upload more than one "coverage.xml" in single step/command?

### ISSUE THREAD

**Issue by ddur** [codecov/example-csharp#7]
I have four separate coverage reports I want to upload in single command. 
"codecov -f" option does not accept wildcards like "c:\reports\OpenCover.*.xml".
As far as I can remember, multiple -f options are not accepted too.

Except examples, I cannot find any documentation or manual for "codecov" command (& arguments)

**Comment by stevepeak** [comment]
Can you try the following. Thanks :+1: 

```
codecov -f "file_one" -f "file_two" ...
```

**Comment by ddur** [comment]
Looks like I remember well. It does not work with multiple -f options. Thanks.
https://ci.appveyor.com/project/ddur/dbcl

**Comment by stevepeak** [comment]
The contents of the upload are:
```
<<<<<< network
# path=c:\projects\dbcl\reports\OpenCover.Diagnostics.xml
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>
<<<<<< EOF
# path=fixes
"$(find . -type f -name '*.kt' -exec grep -nIH '^/\*' {} \;)
<<<<<< EOF
```

It seems to be missing data :) I'll ping you back soon as I'm going to debug this more. Thanks

**Comment by stevepeak** [comment]
@ddur Can you try `codecov -f "file_one file_two"` I misspoke last message. Thanks!

**Comment by ddur** [comment]
Last OpenCover.Diagnostics.xml is empty, that's OK

**Comment by ddur** [comment]
>Can you try codecov -f "file_one file_two" I misspoke last message. Thanks!

I will try that, but that is not good for windows file names with spaces.
Maybe is ```codecov -f "file_one" "file_two"```?
Or ```codecov -f "\"file_one\" \"file_two\""```?
What you think?

**Comment by stevepeak** [comment]
The package splits by spaces...I think escaping them may work. Lets try this: `codecov -f "file\ one file\ two"`. Otherwise I can figure out a new way.

**Comment by ddur** [comment]
I can build on AppVeyor once in hour. I will try all those ways until tomorrow. :smiley:

**Comment by ddur** [comment]
I would not mind much for 4 uploads if each upload is on single line. 
But having 30 lines of echo for each upload is really ugly.
Thanks
