### ISSUE TITLE
Report is attached to a wrong branch

### ISSUE THREAD

**Issue by abaranch** [codecov/example-csharp#9]
I'm trying to integrate CodeCov with our repo. We have C#, msbuild and VS Online for CI.
I followed instruction from the example and locally everything worked as expected.
When I try to integrate it with CI report is uploaded to a master branch rather than my local branch.
My ps script is:

```
..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user "-target:C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "-targetargs:..\bin\Release\src\Adapters.Tests\Tests.dll /logger:trx" -hideskipped:All -output:.\coverage.xml

(New-Object System.Net.WebClient).DownloadFile("https://codecov.io/bash", ".\CodecovUploader.sh")
.\CodecovUploader.sh -f coverage.xml -t $env:CODECOVACCESSKEY -X gcov
```
VS Online shows me that I compiled my branch (it actually would not work in any other since I have CodeCov integration only in that branch). CodeCov.io shows that branch is master.

Please suggest why that may happen.

**Comment by stevepeak** [comment]
You can [change the branch][1] via `-B branch`. In linux we would call `-B $(git rev-parse --abbrev-ref HEAD)` but not sure how to translate that into Batch.

[1]: https://github.com/codecov/codecov-bash/blob/346e91cb2918fd1d84fde46c0814ae2005fee363/codecov#L64

**Comment by abaranch** [comment]
Thank you for the suggestion. 
Apparently VSO does something weird because your command returns just "HEAD".

On the agent box after the build I get this: 
```
git branch
* (HEAD detached at 3cff89a)
  master
```

And in VSO build logs I see this:
```
Running 'git reset --hard HEAD' on C:\Builds\CoreSDK\3\s.
HEAD is now at e8c4249 Switch to vstest.console.exe; add all tests
Starting fetch
Checking out 3cff89a4142ea72141f948efe3622b25ac0a5b60 to C:\Builds\CoreSDK\3\s
Checked out branch refs/heads/abaranch/tryCodeCov for repository XXX at commit 3cff89a4142ea72141f948efe3622b25ac0a5b60
```

I will try to find out a way to get a branch name and post back...

**Comment by abaranch** [comment]
Ok, figured that out. Thank you for the suggestion.
Looks hacky but works
$lastCommit = $(git rev-parse HEAD)
$branchName = $(git branch --all --contains $lastCommit)[1].Trim().Substring("remotes/origin/".Length)

**Comment by stevepeak** [comment]
Thanks! We are looking to integrate with VS this year, so this process should be much better soon. Cheers!
